# Generated by Django 4.0.5 on 2022-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('completedAt', models.DateTimeField()),
            ],
        ),
    ]
